"""
Knowledge base for retrieval-augmented generation (RAG).

Covers 500+ topics across world capitals, Indian states/cities, science and general
knowledge concepts, notable tech companies, notable historical/public figures, sports,
geography, astronomy, literature, awards, religions, and more. Retrieval is deliberately
simple (keyword overlap, not embeddings) so the mechanism is easy to explain and verify --
swapping in an embedding-based retriever would be the natural next step, without changing
anything downstream in generate.py.
"""

KNOWLEDGE_BASE = [
    {"keywords": ["france", "paris"], "text": "Paris is the capital of France."},
    {"keywords": ["japan", "tokyo"], "text": "Tokyo is the capital of Japan."},
    {"keywords": ["germany", "berlin"], "text": "Berlin is the capital of Germany."},
    {"keywords": ["italy", "rome"], "text": "Rome is the capital of Italy."},
    {"keywords": ["spain", "madrid"], "text": "Madrid is the capital of Spain."},
    {"keywords": ["united kingdom", "london"], "text": "London is the capital of United Kingdom."},
    {"keywords": ["russia", "moscow"], "text": "Moscow is the capital of Russia."},
    {"keywords": ["china", "beijing"], "text": "Beijing is the capital of China."},
    {"keywords": ["united states", "washington"], "text": "Washington, D.C. is the capital of United States."},
    {"keywords": ["canada", "ottawa"], "text": "Ottawa is the capital of Canada."},
    {"keywords": ["australia", "canberra"], "text": "Canberra is the capital of Australia."},
    {"keywords": ["brazil", "brasilia"], "text": "Brasilia is the capital of Brazil."},
    {"keywords": ["mexico", "mexico"], "text": "Mexico City is the capital of Mexico."},
    {"keywords": ["egypt", "cairo"], "text": "Cairo is the capital of Egypt."},
    {"keywords": ["south africa", "pretoria"], "text": "Pretoria is the capital of South Africa."},
    {"keywords": ["nigeria", "abuja"], "text": "Abuja is the capital of Nigeria."},
    {"keywords": ["kenya", "nairobi"], "text": "Nairobi is the capital of Kenya."},
    {"keywords": ["argentina", "buenos"], "text": "Buenos Aires is the capital of Argentina."},
    {"keywords": ["chile", "santiago"], "text": "Santiago is the capital of Chile."},
    {"keywords": ["peru", "lima"], "text": "Lima is the capital of Peru."},
    {"keywords": ["colombia", "bogota"], "text": "Bogota is the capital of Colombia."},
    {"keywords": ["venezuela", "caracas"], "text": "Caracas is the capital of Venezuela."},
    {"keywords": ["cuba", "havana"], "text": "Havana is the capital of Cuba."},
    {"keywords": ["greece", "athens"], "text": "Athens is the capital of Greece."},
    {"keywords": ["turkey", "ankara"], "text": "Ankara is the capital of Turkey."},
    {"keywords": ["portugal", "lisbon"], "text": "Lisbon is the capital of Portugal."},
    {"keywords": ["netherlands", "amsterdam"], "text": "Amsterdam is the capital of Netherlands."},
    {"keywords": ["belgium", "brussels"], "text": "Brussels is the capital of Belgium."},
    {"keywords": ["switzerland", "bern"], "text": "Bern is the capital of Switzerland."},
    {"keywords": ["austria", "vienna"], "text": "Vienna is the capital of Austria."},
    {"keywords": ["sweden", "stockholm"], "text": "Stockholm is the capital of Sweden."},
    {"keywords": ["norway", "oslo"], "text": "Oslo is the capital of Norway."},
    {"keywords": ["denmark", "copenhagen"], "text": "Copenhagen is the capital of Denmark."},
    {"keywords": ["finland", "helsinki"], "text": "Helsinki is the capital of Finland."},
    {"keywords": ["poland", "warsaw"], "text": "Warsaw is the capital of Poland."},
    {"keywords": ["ukraine", "kyiv"], "text": "Kyiv is the capital of Ukraine."},
    {"keywords": ["czech republic", "prague"], "text": "Prague is the capital of Czech Republic."},
    {"keywords": ["hungary", "budapest"], "text": "Budapest is the capital of Hungary."},
    {"keywords": ["romania", "bucharest"], "text": "Bucharest is the capital of Romania."},
    {"keywords": ["ireland", "dublin"], "text": "Dublin is the capital of Ireland."},
    {"keywords": ["iceland", "reykjavik"], "text": "Reykjavik is the capital of Iceland."},
    {"keywords": ["israel", "jerusalem"], "text": "Jerusalem is the capital of Israel."},
    {"keywords": ["saudi arabia", "riyadh"], "text": "Riyadh is the capital of Saudi Arabia."},
    {"keywords": ["united arab emirates", "abu"], "text": "Abu Dhabi is the capital of United Arab Emirates."},
    {"keywords": ["qatar", "doha"], "text": "Doha is the capital of Qatar."},
    {"keywords": ["iran", "tehran"], "text": "Tehran is the capital of Iran."},
    {"keywords": ["iraq", "baghdad"], "text": "Baghdad is the capital of Iraq."},
    {"keywords": ["pakistan", "islamabad"], "text": "Islamabad is the capital of Pakistan."},
    {"keywords": ["bangladesh", "dhaka"], "text": "Dhaka is the capital of Bangladesh."},
    {"keywords": ["sri lanka", "colombo"], "text": "Colombo is the capital of Sri Lanka."},
    {"keywords": ["nepal", "kathmandu"], "text": "Kathmandu is the capital of Nepal."},
    {"keywords": ["bhutan", "thimphu"], "text": "Thimphu is the capital of Bhutan."},
    {"keywords": ["myanmar", "naypyidaw"], "text": "Naypyidaw is the capital of Myanmar."},
    {"keywords": ["thailand", "bangkok"], "text": "Bangkok is the capital of Thailand."},
    {"keywords": ["vietnam", "hanoi"], "text": "Hanoi is the capital of Vietnam."},
    {"keywords": ["cambodia", "phnom"], "text": "Phnom Penh is the capital of Cambodia."},
    {"keywords": ["laos", "vientiane"], "text": "Vientiane is the capital of Laos."},
    {"keywords": ["malaysia", "kuala"], "text": "Kuala Lumpur is the capital of Malaysia."},
    {"keywords": ["singapore", "singapore"], "text": "Singapore is the capital of Singapore."},
    {"keywords": ["indonesia", "jakarta"], "text": "Jakarta is the capital of Indonesia."},
    {"keywords": ["philippines", "manila"], "text": "Manila is the capital of Philippines."},
    {"keywords": ["south korea", "seoul"], "text": "Seoul is the capital of South Korea."},
    {"keywords": ["north korea", "pyongyang"], "text": "Pyongyang is the capital of North Korea."},
    {"keywords": ["mongolia", "ulaanbaatar"], "text": "Ulaanbaatar is the capital of Mongolia."},
    {"keywords": ["kazakhstan", "astana"], "text": "Astana is the capital of Kazakhstan."},
    {"keywords": ["afghanistan", "kabul"], "text": "Kabul is the capital of Afghanistan."},
    {"keywords": ["new zealand", "wellington"], "text": "Wellington is the capital of New Zealand."},
    {"keywords": ["fiji", "suva"], "text": "Suva is the capital of Fiji."},
    {"keywords": ["morocco", "rabat"], "text": "Rabat is the capital of Morocco."},
    {"keywords": ["algeria", "algiers"], "text": "Algiers is the capital of Algeria."},
    {"keywords": ["tunisia", "tunis"], "text": "Tunis is the capital of Tunisia."},
    {"keywords": ["libya", "tripoli"], "text": "Tripoli is the capital of Libya."},
    {"keywords": ["ethiopia", "addis"], "text": "Addis Ababa is the capital of Ethiopia."},
    {"keywords": ["ghana", "accra"], "text": "Accra is the capital of Ghana."},
    {"keywords": ["tanzania", "dodoma"], "text": "Dodoma is the capital of Tanzania."},
    {"keywords": ["uganda", "kampala"], "text": "Kampala is the capital of Uganda."},
    {"keywords": ["zimbabwe", "harare"], "text": "Harare is the capital of Zimbabwe."},
    {"keywords": ["zambia", "lusaka"], "text": "Lusaka is the capital of Zambia."},
    {"keywords": ["angola", "luanda"], "text": "Luanda is the capital of Angola."},
    {"keywords": ["mozambique", "maputo"], "text": "Maputo is the capital of Mozambique."},
    {"keywords": ["senegal", "dakar"], "text": "Dakar is the capital of Senegal."},
    {"keywords": ["ivory coast", "yamoussoukro"], "text": "Yamoussoukro is the capital of Ivory Coast."},
    {"keywords": ["cameroon", "yaounde"], "text": "Yaounde is the capital of Cameroon."},
    {"keywords": ["sudan", "khartoum"], "text": "Khartoum is the capital of Sudan."},
    {"keywords": ["jordan", "amman"], "text": "Amman is the capital of Jordan."},
    {"keywords": ["lebanon", "beirut"], "text": "Beirut is the capital of Lebanon."},
    {"keywords": ["syria", "damascus"], "text": "Damascus is the capital of Syria."},
    {"keywords": ["yemen", "sanaa"], "text": "Sanaa is the capital of Yemen."},
    {"keywords": ["oman", "muscat"], "text": "Muscat is the capital of Oman."},
    {"keywords": ["kuwait", "kuwait"], "text": "Kuwait City is the capital of Kuwait."},
    {"keywords": ["bahrain", "manama"], "text": "Manama is the capital of Bahrain."},
    {"keywords": ["georgia", "tbilisi"], "text": "Tbilisi is the capital of Georgia."},
    {"keywords": ["armenia", "yerevan"], "text": "Yerevan is the capital of Armenia."},
    {"keywords": ["azerbaijan", "baku"], "text": "Baku is the capital of Azerbaijan."},
    {"keywords": ["uzbekistan", "tashkent"], "text": "Tashkent is the capital of Uzbekistan."},
    {"keywords": ["turkmenistan", "ashgabat"], "text": "Ashgabat is the capital of Turkmenistan."},
    {"keywords": ["kyrgyzstan", "bishkek"], "text": "Bishkek is the capital of Kyrgyzstan."},
    {"keywords": ["tajikistan", "dushanbe"], "text": "Dushanbe is the capital of Tajikistan."},
    {"keywords": ["slovakia", "bratislava"], "text": "Bratislava is the capital of Slovakia."},
    {"keywords": ["slovenia", "ljubljana"], "text": "Ljubljana is the capital of Slovenia."},
    {"keywords": ["croatia", "zagreb"], "text": "Zagreb is the capital of Croatia."},
    {"keywords": ["serbia", "belgrade"], "text": "Belgrade is the capital of Serbia."},
    {"keywords": ["bulgaria", "sofia"], "text": "Sofia is the capital of Bulgaria."},
    {"keywords": ["bosnia and herzegovina", "sarajevo"], "text": "Sarajevo is the capital of Bosnia and Herzegovina."},
    {"keywords": ["albania", "tirana"], "text": "Tirana is the capital of Albania."},
    {"keywords": ["estonia", "tallinn"], "text": "Tallinn is the capital of Estonia."},
    {"keywords": ["latvia", "riga"], "text": "Riga is the capital of Latvia."},
    {"keywords": ["lithuania", "vilnius"], "text": "Vilnius is the capital of Lithuania."},
    {"keywords": ["luxembourg", "luxembourg"], "text": "Luxembourg City is the capital of Luxembourg."},
    {"keywords": ["malta", "valletta"], "text": "Valletta is the capital of Malta."},
    {"keywords": ["cyprus", "nicosia"], "text": "Nicosia is the capital of Cyprus."},
    {"keywords": ["monaco", "monaco"], "text": "Monaco is the capital of Monaco."},
    {"keywords": ["karnataka", "bengaluru"], "text": "Bengaluru is the capital of the Indian state of Karnataka."},
    {"keywords": ["maharashtra", "mumbai"], "text": "Mumbai is the capital of the Indian state of Maharashtra."},
    {"keywords": ["tamil nadu", "chennai"], "text": "Chennai is the capital of the Indian state of Tamil Nadu."},
    {"keywords": ["west bengal", "kolkata"], "text": "Kolkata is the capital of the Indian state of West Bengal."},
    {"keywords": ["telangana", "hyderabad"], "text": "Hyderabad is the capital of the Indian state of Telangana."},
    {"keywords": ["andhra pradesh", "amaravati"], "text": "Amaravati is the capital of the Indian state of Andhra Pradesh."},
    {"keywords": ["kerala", "thiruvananthapuram"], "text": "Thiruvananthapuram is the capital of the Indian state of Kerala."},
    {"keywords": ["gujarat", "gandhinagar"], "text": "Gandhinagar is the capital of the Indian state of Gujarat."},
    {"keywords": ["rajasthan", "jaipur"], "text": "Jaipur is the capital of the Indian state of Rajasthan."},
    {"keywords": ["punjab", "chandigarh"], "text": "Chandigarh is the capital of the Indian state of Punjab."},
    {"keywords": ["haryana", "chandigarh"], "text": "Chandigarh is the capital of the Indian state of Haryana."},
    {"keywords": ["uttar pradesh", "lucknow"], "text": "Lucknow is the capital of the Indian state of Uttar Pradesh."},
    {"keywords": ["bihar", "patna"], "text": "Patna is the capital of the Indian state of Bihar."},
    {"keywords": ["madhya pradesh", "bhopal"], "text": "Bhopal is the capital of the Indian state of Madhya Pradesh."},
    {"keywords": ["odisha", "bhubaneswar"], "text": "Bhubaneswar is the capital of the Indian state of Odisha."},
    {"keywords": ["assam", "dispur"], "text": "Dispur is the capital of the Indian state of Assam."},
    {"keywords": ["jharkhand", "ranchi"], "text": "Ranchi is the capital of the Indian state of Jharkhand."},
    {"keywords": ["chhattisgarh", "raipur"], "text": "Raipur is the capital of the Indian state of Chhattisgarh."},
    {"keywords": ["uttarakhand", "dehradun"], "text": "Dehradun is the capital of the Indian state of Uttarakhand."},
    {"keywords": ["himachal pradesh", "shimla"], "text": "Shimla is the capital of the Indian state of Himachal Pradesh."},
    {"keywords": ["goa", "panaji"], "text": "Panaji is the capital of the Indian state of Goa."},
    {"keywords": ["tripura", "agartala"], "text": "Agartala is the capital of the Indian state of Tripura."},
    {"keywords": ["meghalaya", "shillong"], "text": "Shillong is the capital of the Indian state of Meghalaya."},
    {"keywords": ["manipur", "imphal"], "text": "Imphal is the capital of the Indian state of Manipur."},
    {"keywords": ["nagaland", "kohima"], "text": "Kohima is the capital of the Indian state of Nagaland."},
    {"keywords": ["mizoram", "aizawl"], "text": "Aizawl is the capital of the Indian state of Mizoram."},
    {"keywords": ["arunachal pradesh", "itanagar"], "text": "Itanagar is the capital of the Indian state of Arunachal Pradesh."},
    {"keywords": ["sikkim", "gangtok"], "text": "Gangtok is the capital of the Indian state of Sikkim."},
    {"keywords": ["tirupati"], "text": "Tirupati is a city in the Chittoor district of Andhra Pradesh, India, home to the Tirumala Venkateswara Temple, one of the most visited religious pilgrimage sites in the world."},
    {"keywords": ["varanasi"], "text": "Varanasi is an ancient city on the banks of the Ganges River in Uttar Pradesh, India, considered one of the oldest continuously inhabited cities in the world and a major Hindu pilgrimage site."},
    {"keywords": ["agra"], "text": "Agra is a city in Uttar Pradesh, India, famous as the home of the Taj Mahal."},
    {"keywords": ["amritsar"], "text": "Amritsar is a city in Punjab, India, home to the Golden Temple, the holiest shrine in Sikhism."},
    {"keywords": ["jaipur"], "text": "Jaipur, also called the Pink City, is the capital of Rajasthan, India, known for its palaces and forts."},
    {"keywords": ["mysuru"], "text": "Mysuru (Mysore) is a city in Karnataka, India, known for its historic palace and silk industry."},
    {"keywords": ["pune"], "text": "Pune is a major city in Maharashtra, India, known as an educational and IT hub."},
    {"keywords": ["kochi"], "text": "Kochi is a major port city in Kerala, India, on the Arabian Sea coast."},
    {"keywords": ["chandigarh"], "text": "Chandigarh is a union territory in India that serves as the capital of both Punjab and Haryana."},
    {"keywords": ["new delhi"], "text": "New Delhi is the capital of India."},
    {"keywords": ["photosynthesis"], "text": "Photosynthesis is the process by which plants, algae, and some bacteria convert light energy, usually from the sun, into chemical energy. Using sunlight, water, and carbon dioxide, chlorophyll in plant cells produces glucose and releases oxygen as a byproduct."},
    {"keywords": ["gravity"], "text": "Gravity is the force by which a planet or other body draws objects toward its center. Earth's gravity gives weight to physical objects and causes them to fall toward the ground when dropped."},
    {"keywords": ["photosynthesis", "oxygen"], "text": "Oxygen released during photosynthesis is a byproduct of the light-dependent reactions, where water molecules are split to provide electrons."},
    {"keywords": ["water", "cycle"], "text": "The water cycle describes the continuous movement of water through evaporation, condensation, precipitation, and collection on Earth."},
    {"keywords": ["dna"], "text": "DNA (deoxyribonucleic acid) is the molecule that carries genetic instructions for the development, functioning, and reproduction of all known living organisms."},
    {"keywords": ["evolution"], "text": "Evolution is the process by which species of organisms change over successive generations through mechanisms such as natural selection."},
    {"keywords": ["solar", "system"], "text": "The solar system consists of the Sun and everything that orbits it, including eight planets, their moons, dwarf planets, asteroids, and comets."},
    {"keywords": ["black", "hole"], "text": "A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape from it."},
    {"keywords": ["electricity"], "text": "Electricity is a form of energy resulting from the flow of electric charge, typically carried by electrons through a conductor."},
    {"keywords": ["climate", "change"], "text": "Climate change refers to long-term shifts in temperatures and weather patterns, largely driven by human activities such as burning fossil fuels since the 19th century."},
    {"keywords": ["vaccine"], "text": "A vaccine works by training the immune system to recognize and fight a specific pathogen by introducing a harmless component of it, such as a weakened or inactivated form."},
    {"keywords": ["artificial", "intelligence"], "text": "Artificial intelligence (AI) refers to computer systems designed to perform tasks that typically require human intelligence, such as learning, reasoning, and problem-solving."},
    {"keywords": ["machine", "learning"], "text": "Machine learning is a subset of artificial intelligence where systems learn patterns from data rather than being explicitly programmed for a specific task."},
    {"keywords": ["internet"], "text": "The internet is a global network of interconnected computers that communicate using standardized protocols, enabling the World Wide Web, email, and other services."},
    {"keywords": ["gdp"], "text": "GDP (Gross Domestic Product) is the total monetary value of all goods and services produced within a country in a given period, commonly used to measure economic size."},
    {"keywords": ["google"], "text": "Google is a multinational technology company founded by Larry Page and Sergey Brin in 1998, best known for its search engine and other internet services. It is headquartered in Mountain View, California."},
    {"keywords": ["microsoft"], "text": "Microsoft is a multinational technology company founded by Bill Gates and Paul Allen in 1975, known for the Windows operating system and Office software. It is headquartered in Redmond, Washington."},
    {"keywords": ["apple"], "text": "Apple Inc. is a multinational technology company founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in 1976, known for the iPhone, Mac, and other consumer electronics. It is headquartered in Cupertino, California."},
    {"keywords": ["amazon"], "text": "Amazon is a multinational technology and e-commerce company founded by Jeff Bezos in 1994. It is headquartered in Seattle, Washington."},
    {"keywords": ["meta", "facebook"], "text": "Meta (formerly Facebook) is a technology company founded by Mark Zuckerberg in 2004, known for its social media platforms. It is headquartered in Menlo Park, California."},
    {"keywords": ["tesla"], "text": "Tesla is an electric vehicle and clean energy company led by Elon Musk, headquartered in Austin, Texas."},
    {"keywords": ["netflix"], "text": "Netflix is a streaming entertainment company founded by Reed Hastings and Marc Randolph in 1997, headquartered in Los Gatos, California."},
    {"keywords": ["anthropic", "claude"], "text": "Anthropic is an AI safety company that created the Claude family of AI models, founded in 2021 by former OpenAI researchers including Dario Amodei and Daniela Amodei."},
    {"keywords": ["openai", "chatgpt"], "text": "OpenAI is an AI research company known for creating ChatGPT and the GPT series of language models, founded in 2015."},
    {"keywords": ["infosys"], "text": "Infosys is a multinational IT services and consulting company headquartered in Bengaluru, India, co-founded by N. R. Narayana Murthy in 1981."},
    {"keywords": ["tcs"], "text": "Tata Consultancy Services (TCS) is an Indian multinational IT services company, part of the Tata Group, headquartered in Mumbai."},
    {"keywords": ["wipro"], "text": "Wipro is an Indian multinational IT services and consulting company headquartered in Bengaluru."},
    {"keywords": ["mahatma", "gandhi"], "text": "Mahatma Gandhi (1869-1948) was the leader of India's non-violent independence movement against British rule."},
    {"keywords": ["albert", "einstein"], "text": "Albert Einstein (1879-1955) was a theoretical physicist best known for developing the theory of relativity."},
    {"keywords": ["isaac", "newton"], "text": "Isaac Newton (1642-1727) was an English physicist and mathematician known for his laws of motion and universal gravitation."},
    {"keywords": ["abraham", "lincoln"], "text": "Abraham Lincoln (1809-1865) was the 16th President of the United States, known for leading the country through the Civil War and abolishing slavery."},
    {"keywords": ["narendra", "modi"], "text": "Narendra Modi has served as Prime Minister of India since 2014."},
    {"keywords": ["cristiano", "ronaldo"], "text": "Cristiano Ronaldo is a Portuguese professional footballer widely regarded as one of the greatest players of all time, having played for clubs including Manchester United, Real Madrid, and Juventus."},
    {"keywords": ["lionel", "messi"], "text": "Lionel Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time, known for his time at FC Barcelona and Paris Saint-Germain."},
    {"keywords": ["marie", "curie"], "text": "Marie Curie (1867-1934) was a physicist and chemist who conducted pioneering research on radioactivity and was the first woman to win a Nobel Prize."},
    {"keywords": ["apj", "abdul", "kalam"], "text": "A. P. J. Abdul Kalam served as the 11th President of India from 2002 to 2007 and was known as the 'Missile Man of India' for his work in aerospace engineering."},
    {"keywords": ["elon", "musk"], "text": "Elon Musk is a businessman known for leading companies including Tesla and SpaceX."},
    {"keywords": ["panama", "panama"], "text": "Panama City is the capital of Panama."},
    {"keywords": ["costa rica", "san"], "text": "San Jose is the capital of Costa Rica."},
    {"keywords": ["guatemala", "guatemala"], "text": "Guatemala City is the capital of Guatemala."},
    {"keywords": ["honduras", "tegucigalpa"], "text": "Tegucigalpa is the capital of Honduras."},
    {"keywords": ["nicaragua", "managua"], "text": "Managua is the capital of Nicaragua."},
    {"keywords": ["el salvador", "san"], "text": "San Salvador is the capital of El Salvador."},
    {"keywords": ["ecuador", "quito"], "text": "Quito is the capital of Ecuador."},
    {"keywords": ["bolivia", "sucre"], "text": "Sucre is the capital of Bolivia."},
    {"keywords": ["uruguay", "montevideo"], "text": "Montevideo is the capital of Uruguay."},
    {"keywords": ["paraguay", "asuncion"], "text": "Asuncion is the capital of Paraguay."},
    {"keywords": ["everest", "mount", "everest"], "text": "Mount Everest, located in the Himalayas on the border of Nepal and China (Tibet), is Earth's highest mountain above sea level at 8,849 meters."},
    {"keywords": ["amazon", "river"], "text": "The Amazon River in South America is the largest river by discharge volume of water in the world."},
    {"keywords": ["sahara", "desert"], "text": "The Sahara is the largest hot desert in the world, spanning much of North Africa."},
    {"keywords": ["great", "wall", "china"], "text": "The Great Wall of China is a series of fortifications built across the historical northern borders of China, originally to protect against invasions."},
    {"keywords": ["taj", "mahal"], "text": "The Taj Mahal is an ivory-white marble mausoleum in Agra, India, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal."},
    {"keywords": ["eiffel", "tower"], "text": "The Eiffel Tower is a wrought-iron lattice tower in Paris, France, completed in 1889 and named after engineer Gustave Eiffel."},
    {"keywords": ["great", "barrier", "reef"], "text": "The Great Barrier Reef, off the coast of Queensland, Australia, is the world's largest coral reef system."},
    {"keywords": ["olympics"], "text": "The Olympic Games are an international multi-sport event held every four years, organized by the International Olympic Committee."},
    {"keywords": ["world", "war", "2"], "text": "World War II (1939-1945) was a global conflict involving most of the world's nations, ending with the defeat of Nazi Germany and Imperial Japan."},
    {"keywords": ["united", "nations"], "text": "The United Nations is an intergovernmental organization founded in 1945 to maintain international peace and security, headquartered in New York City."},
    {"keywords": ["cricket", "world", "cup"], "text": "The Cricket World Cup is the international championship of One Day International cricket, organized by the International Cricket Council."},
    {"keywords": ["isro"], "text": "ISRO (Indian Space Research Organisation) is India's national space agency, headquartered in Bengaluru, known for missions including Chandrayaan and Mangalyaan."},
    {"keywords": ["nasa"], "text": "NASA (National Aeronautics and Space Administration) is the United States' space agency, responsible for the civilian space program and aerospace research."},
    {"keywords": ["hydrogen"], "text": "Hydrogen is the lightest and most abundant chemical element in the universe, with the atomic symbol H and atomic number 1."},
    {"keywords": ["helium"], "text": "Helium is a light, inert noble gas with atomic number 2, commonly used in balloons and as a coolant for superconducting magnets."},
    {"keywords": ["oxygen"], "text": "Oxygen is a chemical element with symbol O and atomic number 8, essential for respiration in most living organisms."},
    {"keywords": ["carbon"], "text": "Carbon is a chemical element with symbol C and atomic number 6, forming the structural basis of all known organic life."},
    {"keywords": ["nitrogen"], "text": "Nitrogen is a chemical element with symbol N and atomic number 7, making up about 78 percent of Earth's atmosphere."},
    {"keywords": ["gold"], "text": "Gold is a dense, precious metal with symbol Au and atomic number 79, valued for jewelry, currency reserves, and electronics."},
    {"keywords": ["silver"], "text": "Silver is a precious metal with symbol Ag and atomic number 47, known for its high electrical and thermal conductivity."},
    {"keywords": ["iron"], "text": "Iron is a metallic element with symbol Fe and atomic number 26, widely used in construction and the production of steel."},
    {"keywords": ["copper"], "text": "Copper is a metallic element with symbol Cu and atomic number 29, prized for its electrical conductivity and used extensively in wiring."},
    {"keywords": ["aluminium", "aluminum"], "text": "Aluminium (aluminum) is a lightweight metallic element with symbol Al and atomic number 13, widely used in packaging and aerospace."},
    {"keywords": ["sodium"], "text": "Sodium is a reactive alkali metal with symbol Na and atomic number 11, essential for nerve function in the human body."},
    {"keywords": ["potassium"], "text": "Potassium is an alkali metal with symbol K and atomic number 19, important for muscle and nerve function in living organisms."},
    {"keywords": ["calcium"], "text": "Calcium is an alkaline earth metal with symbol Ca and atomic number 20, essential for building bones and teeth."},
    {"keywords": ["zinc"], "text": "Zinc is a metallic element with symbol Zn and atomic number 30, used in galvanizing steel and as an essential dietary mineral."},
    {"keywords": ["lead", "metal"], "text": "Lead is a dense, soft metal with symbol Pb and atomic number 82, historically used in pipes, paint, and batteries."},
    {"keywords": ["mercury", "element"], "text": "Mercury is a heavy, silvery metal with symbol Hg and atomic number 80 that is liquid at room temperature."},
    {"keywords": ["uranium"], "text": "Uranium is a radioactive metallic element with symbol U and atomic number 92, used as fuel in nuclear reactors and weapons."},
    {"keywords": ["silicon"], "text": "Silicon is a metalloid element with symbol Si and atomic number 14, forming the basis of most semiconductor electronics."},
    {"keywords": ["chlorine"], "text": "Chlorine is a reactive halogen gas with symbol Cl and atomic number 17, commonly used for water disinfection."},
    {"keywords": ["titanium"], "text": "Titanium is a strong, lightweight metal with symbol Ti and atomic number 22, used in aerospace, medical implants, and alloys."},
    {"keywords": ["platinum"], "text": "Platinum is a dense, precious metal with symbol Pt and atomic number 78, used in jewelry, catalytic converters, and electronics."},
    {"keywords": ["periodic", "table"], "text": "The periodic table organizes chemical elements by increasing atomic number, grouping them by similar chemical properties into rows and columns."},
    {"keywords": ["python", "programming"], "text": "Python is a high-level, general-purpose programming language known for its readable syntax, widely used in web development, data science, and AI."},
    {"keywords": ["java", "programming"], "text": "Java is a class-based, object-oriented programming language designed to run on any platform via the Java Virtual Machine."},
    {"keywords": ["javascript"], "text": "JavaScript is a high-level scripting language primarily used to create interactive behavior on web pages, and also runs on servers via Node.js."},
    {"keywords": ["c++", "programming"], "text": "C++ is a general-purpose, compiled programming language that extends C with object-oriented features, widely used in systems and game development."},
    {"keywords": ["ruby", "programming"], "text": "Ruby is a dynamic, object-oriented programming language known for its simplicity and popularity through the Ruby on Rails web framework."},
    {"keywords": ["golang", "go", "programming"], "text": "Go (Golang) is an open-source, statically typed programming language developed by Google, known for simplicity and strong support for concurrency."},
    {"keywords": ["rust", "programming"], "text": "Rust is a systems programming language focused on memory safety and performance without a garbage collector, developed originally at Mozilla."},
    {"keywords": ["swift", "programming"], "text": "Swift is a programming language developed by Apple for building iOS, macOS, watchOS, and tvOS applications."},
    {"keywords": ["kotlin"], "text": "Kotlin is a modern, statically typed programming language that runs on the JVM and is the preferred language for Android app development."},
    {"keywords": ["php"], "text": "PHP is a server-side scripting language widely used for web development, powering platforms such as WordPress."},
    {"keywords": ["sql"], "text": "SQL (Structured Query Language) is a standard language for managing and querying data stored in relational databases."},
    {"keywords": ["html"], "text": "HTML (HyperText Markup Language) is the standard markup language used to structure content on web pages."},
    {"keywords": ["css"], "text": "CSS (Cascading Style Sheets) is a stylesheet language used to describe the visual presentation of HTML documents."},
    {"keywords": ["typescript"], "text": "TypeScript is a statically typed superset of JavaScript developed by Microsoft that compiles down to plain JavaScript."},
    {"keywords": ["algorithm"], "text": "An algorithm is a finite, well-defined sequence of steps used to solve a problem or perform a computation."},
    {"keywords": ["data", "structure"], "text": "A data structure is a specialized format for organizing, storing, and accessing data efficiently, such as arrays, linked lists, trees, and hash maps."},
    {"keywords": ["api"], "text": "An API (Application Programming Interface) is a set of rules that allows different software applications to communicate with one another."},
    {"keywords": ["rest", "api"], "text": "REST (Representational State Transfer) is an architectural style for designing networked APIs that use standard HTTP methods to operate on resources."},
    {"keywords": ["database"], "text": "A database is an organized collection of structured data stored electronically and managed by a database management system (DBMS)."},
    {"keywords": ["cloud", "computing"], "text": "Cloud computing is the delivery of computing services such as servers, storage, and databases over the internet, offered by providers like AWS, Azure, and Google Cloud."},
    {"keywords": ["docker"], "text": "Docker is a platform that uses OS-level virtualization to package applications and their dependencies into portable containers."},
    {"keywords": ["kubernetes"], "text": "Kubernetes is an open-source container orchestration platform used to automate the deployment, scaling, and management of containerized applications."},
    {"keywords": ["microservices"], "text": "Microservices is an architectural style that structures an application as a collection of small, independently deployable services."},
    {"keywords": ["blockchain"], "text": "A blockchain is a distributed, tamper-resistant digital ledger that records transactions across many computers in a chain of cryptographically linked blocks."},
    {"keywords": ["bitcoin"], "text": "Bitcoin is a decentralized digital cryptocurrency created in 2009 by an anonymous person or group using the pseudonym Satoshi Nakamoto."},
    {"keywords": ["encryption"], "text": "Encryption is the process of converting information into a coded form to prevent unauthorized access, reversible only with the correct decryption key."},
    {"keywords": ["cybersecurity"], "text": "Cybersecurity refers to the practices and technologies designed to protect computer systems, networks, and data from digital attacks."},
    {"keywords": ["open", "source"], "text": "Open source software is software whose source code is made publicly available for anyone to view, use, modify, and distribute."},
    {"keywords": ["fastapi"], "text": "FastAPI is a modern, high-performance Python web framework for building APIs, known for automatic documentation and asynchronous support."},
    {"keywords": ["django"], "text": "Django is a high-level Python web framework that encourages rapid development and follows the model-template-views architectural pattern."},
    {"keywords": ["aws"], "text": "Amazon Web Services (AWS) is Amazon's cloud computing platform, offering services such as compute (EC2), storage (S3), and databases."},
    {"keywords": ["rag", "retrieval"], "text": "Retrieval-Augmented Generation (RAG) is a technique that combines a retrieval system with a language model, fetching relevant documents to ground the model's generated responses."},
    {"keywords": ["llm", "large language model"], "text": "A large language model (LLM) is a neural network trained on vast amounts of text data to understand and generate human-like language."},
    {"keywords": ["langchain"], "text": "LangChain is an open-source framework that simplifies building applications powered by large language models, including chains, agents, and retrieval pipelines."},
    {"keywords": ["faiss"], "text": "FAISS (Facebook AI Similarity Search) is an open-source library for efficient similarity search and clustering of dense vector embeddings."},
    {"keywords": ["embeddings"], "text": "Embeddings are dense vector representations of data, such as text or images, that capture semantic meaning in a form usable by machine learning models."},
    {"keywords": ["ibm"], "text": "IBM (International Business Machines) is a multinational technology company known for hardware, software, and consulting services, headquartered in Armonk, New York."},
    {"keywords": ["intel"], "text": "Intel is an American semiconductor company known for manufacturing microprocessors, headquartered in Santa Clara, California."},
    {"keywords": ["nvidia"], "text": "NVIDIA is a technology company known for designing graphics processing units (GPUs) widely used in gaming and AI computing, headquartered in Santa Clara, California."},
    {"keywords": ["oracle", "company"], "text": "Oracle Corporation is a multinational technology company known for database software and cloud services, headquartered in Austin, Texas."},
    {"keywords": ["salesforce"], "text": "Salesforce is a cloud-based software company best known for its customer relationship management (CRM) platform."},
    {"keywords": ["adobe"], "text": "Adobe is a software company known for creative products such as Photoshop, Illustrator, and Acrobat, headquartered in San Jose, California."},
    {"keywords": ["sap"], "text": "SAP is a German multinational software company known for enterprise resource planning (ERP) software."},
    {"keywords": ["samsung"], "text": "Samsung is a South Korean multinational conglomerate known for electronics including smartphones, semiconductors, and appliances."},
    {"keywords": ["sony"], "text": "Sony is a Japanese multinational conglomerate known for consumer electronics, gaming (PlayStation), and entertainment."},
    {"keywords": ["huawei"], "text": "Huawei is a Chinese multinational technology company known for telecommunications equipment and smartphones."},
    {"keywords": ["cisco"], "text": "Cisco Systems is an American technology company known for networking hardware and telecommunications equipment."},
    {"keywords": ["dell"], "text": "Dell is an American technology company known for manufacturing personal computers and servers, founded by Michael Dell."},
    {"keywords": ["twitter", "x corp"], "text": "X (formerly Twitter) is a social media platform for short-form posts, founded in 2006 and later acquired by Elon Musk in 2022."},
    {"keywords": ["linkedin"], "text": "LinkedIn is a professional networking platform used for job searching, recruiting, and business networking, owned by Microsoft."},
    {"keywords": ["uber"], "text": "Uber is a technology company that operates a ride-hailing and delivery platform, founded in 2009 and headquartered in San Francisco."},
    {"keywords": ["airbnb"], "text": "Airbnb is an online marketplace for lodging and travel experiences, connecting hosts with travelers worldwide."},
    {"keywords": ["spotify"], "text": "Spotify is a Swedish audio streaming platform offering music, podcasts, and audiobooks."},
    {"keywords": ["paypal"], "text": "PayPal is an online payments company that enables money transfers and digital payments, co-founded by Elon Musk and Peter Thiel among others."},
    {"keywords": ["napoleon", "bonaparte"], "text": "Napoleon Bonaparte (1769-1821) was a French military leader and emperor who rose to prominence during the French Revolution and led France in a series of European wars."},
    {"keywords": ["julius", "caesar"], "text": "Julius Caesar (100-44 BC) was a Roman general and statesman who played a critical role in the fall of the Roman Republic and rise of the Roman Empire."},
    {"keywords": ["cleopatra"], "text": "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt, known for her alliances with Julius Caesar and Mark Antony."},
    {"keywords": ["winston", "churchill"], "text": "Winston Churchill was Prime Minister of the United Kingdom during World War II, known for his leadership and speeches rallying Britain against Nazi Germany."},
    {"keywords": ["nelson", "mandela"], "text": "Nelson Mandela was an anti-apartheid revolutionary who became South Africa's first Black president in 1994 after 27 years of imprisonment."},
    {"keywords": ["martin", "luther", "king"], "text": "Martin Luther King Jr. was an American civil rights leader known for his nonviolent activism and his 'I Have a Dream' speech."},
    {"keywords": ["john", "kennedy", "jfk"], "text": "John F. Kennedy served as the 35th President of the United States from 1961 until his assassination in 1963."},
    {"keywords": ["barack", "obama"], "text": "Barack Obama served as the 44th President of the United States from 2009 to 2017, the first African American to hold the office."},
    {"keywords": ["queen", "elizabeth"], "text": "Queen Elizabeth II reigned as monarch of the United Kingdom from 1952 until her death in 2022, the longest-reigning British monarch."},
    {"keywords": ["william", "shakespeare"], "text": "William Shakespeare (1564-1616) was an English playwright and poet widely regarded as the greatest writer in the English language, author of works like Hamlet and Macbeth."},
    {"keywords": ["leonardo", "da vinci"], "text": "Leonardo da Vinci (1452-1519) was an Italian Renaissance polymath known for masterpieces like the Mona Lisa and The Last Supper, as well as scientific and engineering studies."},
    {"keywords": ["michelangelo"], "text": "Michelangelo (1475-1564) was an Italian Renaissance sculptor and painter, known for the ceiling of the Sistine Chapel and the statue of David."},
    {"keywords": ["charles", "darwin"], "text": "Charles Darwin (1809-1882) was an English naturalist known for proposing the theory of evolution by natural selection in his book On the Origin of Species."},
    {"keywords": ["nikola", "tesla"], "text": "Nikola Tesla (1856-1943) was a Serbian-American inventor and engineer known for his contributions to alternating current (AC) electrical systems."},
    {"keywords": ["thomas", "edison"], "text": "Thomas Edison (1847-1931) was an American inventor known for developing the practical electric light bulb and the phonograph, among many other inventions."},
    {"keywords": ["alexander", "graham", "bell"], "text": "Alexander Graham Bell was a Scottish-born inventor credited with patenting the first practical telephone in 1876."},
    {"keywords": ["wright", "brothers"], "text": "The Wright Brothers, Orville and Wilbur, were American aviation pioneers credited with inventing and flying the first successful powered airplane in 1903."},
    {"keywords": ["christopher", "columbus"], "text": "Christopher Columbus was an Italian explorer whose 1492 voyage across the Atlantic Ocean led to European awareness of the Americas."},
    {"keywords": ["genghis", "khan"], "text": "Genghis Khan founded the Mongol Empire in the 13th century, becoming the largest contiguous land empire in history."},
    {"keywords": ["alexander", "the great"], "text": "Alexander the Great was a king of ancient Macedon who created one of the largest empires in ancient history by age 30."},
    {"keywords": ["jawaharlal", "nehru"], "text": "Jawaharlal Nehru was the first Prime Minister of independent India, serving from 1947 to 1964."},
    {"keywords": ["sardar", "patel"], "text": "Sardar Vallabhbhai Patel, known as the 'Iron Man of India,' was a key leader in India's independence movement and its first Deputy Prime Minister."},
    {"keywords": ["bhagat", "singh"], "text": "Bhagat Singh was an Indian revolutionary who played a significant role in the fight for India's independence from British rule."},
    {"keywords": ["subhas", "chandra", "bose"], "text": "Subhas Chandra Bose was an Indian nationalist leader who formed the Indian National Army to fight British colonial rule."},
    {"keywords": ["rabindranath", "tagore"], "text": "Rabindranath Tagore was a Bengali polymath and poet who became the first non-European to win the Nobel Prize in Literature, in 1913."},
    {"keywords": ["swami", "vivekananda"], "text": "Swami Vivekananda was an Indian Hindu monk who introduced Vedanta and Yoga philosophy to the Western world in the late 19th century."},
    {"keywords": ["ratan", "tata"], "text": "Ratan Tata is an Indian industrialist who served as chairman of Tata Sons, leading the Tata Group through major global expansion."},
    {"keywords": ["dhirubhai", "ambani"], "text": "Dhirubhai Ambani founded Reliance Industries, building it into one of India's largest conglomerates."},
    {"keywords": ["fifa", "world", "cup"], "text": "The FIFA World Cup is an international football tournament held every four years, contested by national teams from around the world."},
    {"keywords": ["basketball"], "text": "Basketball is a team sport in which two teams of five players score points by shooting a ball through the opposing team's hoop."},
    {"keywords": ["nba"], "text": "The NBA (National Basketball Association) is the premier professional basketball league in North America."},
    {"keywords": ["tennis"], "text": "Tennis is a racket sport played individually or in doubles, with four Grand Slam tournaments: the Australian Open, French Open, Wimbledon, and US Open."},
    {"keywords": ["wimbledon"], "text": "Wimbledon is the oldest tennis tournament in the world, held annually in London and considered one of the sport's four Grand Slam events."},
    {"keywords": ["roger", "federer"], "text": "Roger Federer is a Swiss former professional tennis player widely regarded as one of the greatest of all time, with 20 Grand Slam titles."},
    {"keywords": ["rafael", "nadal"], "text": "Rafael Nadal is a Spanish professional tennis player known for his dominance on clay courts and numerous Grand Slam titles."},
    {"keywords": ["novak", "djokovic"], "text": "Novak Djokovic is a Serbian professional tennis player holding the record for the most Grand Slam men's singles titles."},
    {"keywords": ["sachin", "tendulkar"], "text": "Sachin Tendulkar is a former Indian cricketer widely regarded as one of the greatest batsmen in cricket history, known as the 'God of Cricket' in India."},
    {"keywords": ["virat", "kohli"], "text": "Virat Kohli is an Indian cricketer and former captain of the Indian national team, known for his aggressive batting and consistency."},
    {"keywords": ["ms", "dhoni"], "text": "MS Dhoni is a former Indian cricket captain who led India to victory in the 2007 T20 World Cup and 2011 Cricket World Cup."},
    {"keywords": ["ipl"], "text": "The Indian Premier League (IPL) is a professional Twenty20 cricket league in India, founded in 2008, featuring franchise teams from Indian cities."},
    {"keywords": ["badminton"], "text": "Badminton is a racket sport played with a shuttlecock, popular in countries including India, China, and Indonesia."},
    {"keywords": ["pv", "sindhu"], "text": "PV Sindhu is an Indian badminton player and Olympic medalist, one of India's most successful female athletes."},
    {"keywords": ["chess"], "text": "Chess is a two-player strategy board game played on an 8x8 grid, one of the oldest and most popular games in the world."},
    {"keywords": ["viswanathan", "anand"], "text": "Viswanathan Anand is an Indian chess grandmaster and five-time World Chess Champion."},
    {"keywords": ["formula", "1", "f1"], "text": "Formula 1 (F1) is the highest class of international single-seater auto racing, featuring a world championship for drivers and constructors."},
    {"keywords": ["usain", "bolt"], "text": "Usain Bolt is a retired Jamaican sprinter widely regarded as the fastest human ever recorded, holding world records in the 100m and 200m."},
    {"keywords": ["nile", "river"], "text": "The Nile River in northeastern Africa is traditionally considered the longest river in the world, flowing through Egypt and Sudan."},
    {"keywords": ["ganges", "river"], "text": "The Ganges is a sacred river in India, flowing from the Himalayas through northern India into Bangladesh."},
    {"keywords": ["yangtze", "river"], "text": "The Yangtze River is the longest river in Asia, flowing entirely within China."},
    {"keywords": ["mississippi", "river"], "text": "The Mississippi River is the second-longest river in North America, flowing through the central United States."},
    {"keywords": ["himalayas"], "text": "The Himalayas are a mountain range in Asia separating the plains of the Indian subcontinent from the Tibetan Plateau, home to Mount Everest."},
    {"keywords": ["alps"], "text": "The Alps are a mountain range in Europe stretching across countries including France, Switzerland, Italy, and Austria."},
    {"keywords": ["andes"], "text": "The Andes is the longest continental mountain range in the world, running along the western edge of South America."},
    {"keywords": ["rocky", "mountains"], "text": "The Rocky Mountains are a major mountain range in western North America, stretching from Canada to New Mexico."},
    {"keywords": ["pacific", "ocean"], "text": "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions, extending from the Arctic to the Southern Ocean."},
    {"keywords": ["atlantic", "ocean"], "text": "The Atlantic Ocean is the second-largest ocean on Earth, separating the Americas from Europe and Africa."},
    {"keywords": ["indian", "ocean"], "text": "The Indian Ocean is the third-largest ocean on Earth, bordered by Africa, Asia, and Australia."},
    {"keywords": ["arctic", "ocean"], "text": "The Arctic Ocean is the smallest and shallowest of the world's oceans, located around the North Pole."},
    {"keywords": ["dead", "sea"], "text": "The Dead Sea is a salt lake bordering Jordan and Israel, notable for its extremely high salinity that allows swimmers to float easily."},
    {"keywords": ["caspian", "sea"], "text": "The Caspian Sea is the largest inland body of water in the world, bordered by five countries including Russia and Iran."},
    {"keywords": ["lake", "victoria"], "text": "Lake Victoria is the largest lake in Africa by surface area, bordered by Uganda, Kenya, and Tanzania."},
    {"keywords": ["lake", "baikal"], "text": "Lake Baikal in Siberia, Russia, is the deepest and oldest freshwater lake in the world."},
    {"keywords": ["k2", "mountain"], "text": "K2 is the second-highest mountain on Earth, located on the border between Pakistan and China, known for being extremely difficult to climb."},
    {"keywords": ["kilimanjaro"], "text": "Mount Kilimanjaro in Tanzania is the highest mountain in Africa and the world's tallest free-standing mountain."},
    {"keywords": ["grand", "canyon"], "text": "The Grand Canyon is a steep-sided canyon carved by the Colorado River in Arizona, United States, renowned for its immense scale and colorful rock layers."},
    {"keywords": ["niagara", "falls"], "text": "Niagara Falls consists of three waterfalls on the border between Canada and the United States, a major tourist attraction and hydroelectric power source."},
    {"keywords": ["sun", "star"], "text": "The Sun is the star at the center of the solar system, a nearly perfect sphere of hot plasma that provides Earth with light and heat."},
    {"keywords": ["moon"], "text": "The Moon is Earth's only natural satellite, influencing tides and being the first celestial body humans landed on, in 1969."},
    {"keywords": ["mars", "planet"], "text": "Mars is the fourth planet from the Sun, known as the 'Red Planet' due to iron oxide on its surface, and a major target for space exploration."},
    {"keywords": ["jupiter", "planet"], "text": "Jupiter is the largest planet in the solar system, a gas giant known for its Great Red Spot storm and many moons."},
    {"keywords": ["saturn", "planet"], "text": "Saturn is the sixth planet from the Sun, famous for its prominent ring system made of ice and rock particles."},
    {"keywords": ["venus", "planet"], "text": "Venus is the second planet from the Sun, similar in size to Earth but with a thick, toxic atmosphere and extreme surface heat."},
    {"keywords": ["neptune", "planet"], "text": "Neptune is the eighth and farthest known planet from the Sun, a blue ice giant with strong winds."},
    {"keywords": ["uranus", "planet"], "text": "Uranus is the seventh planet from the Sun, an ice giant notable for rotating on its side."},
    {"keywords": ["pluto"], "text": "Pluto is a dwarf planet in the Kuiper Belt, reclassified from a full planet by the International Astronomical Union in 2006."},
    {"keywords": ["milky", "way"], "text": "The Milky Way is the galaxy that contains our solar system, a barred spiral galaxy with hundreds of billions of stars."},
    {"keywords": ["galaxy"], "text": "A galaxy is a massive system of stars, gas, dust, and dark matter bound together by gravity."},
    {"keywords": ["comet"], "text": "A comet is an icy small solar system body that, when passing close to the Sun, releases gas and dust forming a visible atmosphere and tail."},
    {"keywords": ["asteroid"], "text": "An asteroid is a small rocky body orbiting the Sun, most commonly found in the asteroid belt between Mars and Jupiter."},
    {"keywords": ["light", "year"], "text": "A light-year is a unit of astronomical distance equal to the distance light travels in one year, about 9.46 trillion kilometers."},
    {"keywords": ["big", "bang"], "text": "The Big Bang theory describes the origin of the universe from an extremely hot, dense initial state approximately 13.8 billion years ago."},
    {"keywords": ["exoplanet"], "text": "An exoplanet is a planet located outside our solar system, orbiting a star other than the Sun."},
    {"keywords": ["international", "space", "station", "iss"], "text": "The International Space Station (ISS) is a modular space station in low Earth orbit, a collaborative project involving NASA, Roscosmos, ESA, JAXA, and CSA."},
    {"keywords": ["heart", "organ"], "text": "The human heart is a muscular organ that pumps blood through the circulatory system, beating roughly 100,000 times a day."},
    {"keywords": ["brain", "organ"], "text": "The human brain is the central organ of the nervous system, responsible for thought, memory, emotion, and control of the body."},
    {"keywords": ["lungs"], "text": "The lungs are the primary organs of the respiratory system, responsible for exchanging oxygen and carbon dioxide between the air and blood."},
    {"keywords": ["liver"], "text": "The liver is a vital organ that detoxifies chemicals, metabolizes nutrients, and produces bile to aid digestion."},
    {"keywords": ["kidney"], "text": "The kidneys are paired organs that filter waste products from the blood and regulate fluid balance, producing urine."},
    {"keywords": ["skeleton", "bones"], "text": "The human skeleton consists of 206 bones in adulthood, providing structural support, protection for organs, and enabling movement."},
    {"keywords": ["immune", "system"], "text": "The immune system is a network of cells, tissues, and organs that defends the body against infections and foreign invaders."},
    {"keywords": ["nervous", "system"], "text": "The nervous system, comprising the brain, spinal cord, and nerves, controls and coordinates body functions and processes sensory information."},
    {"keywords": ["digestive", "system"], "text": "The digestive system breaks down food into nutrients the body can absorb, involving organs like the stomach, intestines, and pancreas."},
    {"keywords": ["genes", "gene"], "text": "A gene is a segment of DNA that contains the instructions for producing a specific protein or functional RNA molecule, forming the basic unit of heredity."},
    {"keywords": ["indus", "valley", "civilization"], "text": "The Indus Valley Civilization was a Bronze Age civilization in the northwestern regions of South Asia, known for advanced urban planning at sites like Mohenjo-daro and Harappa."},
    {"keywords": ["maurya", "empire"], "text": "The Maurya Empire was an ancient Indian empire founded by Chandragupta Maurya around 322 BCE, later ruled by the famous emperor Ashoka."},
    {"keywords": ["ashoka"], "text": "Ashoka the Great was a Mauryan emperor who ruled most of the Indian subcontinent and is known for embracing Buddhism and promoting nonviolence."},
    {"keywords": ["mughal", "empire"], "text": "The Mughal Empire was a powerful Muslim dynasty that ruled much of the Indian subcontinent from the 16th to 19th centuries."},
    {"keywords": ["akbar"], "text": "Akbar was the third Mughal emperor, known for his policies of religious tolerance and administrative reforms."},
    {"keywords": ["british", "raj"], "text": "The British Raj refers to British Crown rule over the Indian subcontinent from 1858 until Indian independence in 1947."},
    {"keywords": ["indian", "independence", "1947"], "text": "India gained independence from British colonial rule on August 15, 1947, after a prolonged nonviolent freedom struggle."},
    {"keywords": ["partition", "india"], "text": "The Partition of India in 1947 divided British India into two independent nations, India and Pakistan, resulting in mass migration and violence."},
    {"keywords": ["indian", "constitution"], "text": "The Constitution of India, adopted on 26 January 1950, is the longest written national constitution in the world, primarily drafted by B. R. Ambedkar's committee."},
    {"keywords": ["quit", "india", "movement"], "text": "The Quit India Movement, launched by Mahatma Gandhi in 1942, was a mass civil disobedience campaign demanding an end to British rule in India."},
    {"keywords": ["salt", "march"], "text": "The Salt March of 1930, led by Mahatma Gandhi, was a nonviolent protest against the British salt tax, sparking widespread civil disobedience."},
    {"keywords": ["indian", "national", "congress"], "text": "The Indian National Congress is one of India's oldest political parties, founded in 1885 and central to the independence movement."},
    {"keywords": ["bharatiya", "janata", "party", "bjp"], "text": "The Bharatiya Janata Party (BJP) is a major Indian political party, currently led by Narendra Modi as Prime Minister."},
    {"keywords": ["french", "revolution"], "text": "The French Revolution (1789-1799) was a period of radical political and social upheaval in France that ended the monarchy and led to the rise of Napoleon."},
    {"keywords": ["american", "revolution"], "text": "The American Revolution (1775-1783) was the war in which the thirteen American colonies won independence from British rule."},
    {"keywords": ["industrial", "revolution"], "text": "The Industrial Revolution, beginning in the late 18th century in Britain, was a period of major industrialization and technological change."},
    {"keywords": ["cold", "war"], "text": "The Cold War (1947-1991) was a period of geopolitical tension between the United States and the Soviet Union and their respective allies."},
    {"keywords": ["berlin", "wall"], "text": "The Berlin Wall was a barrier built in 1961 dividing East and West Berlin, becoming a symbol of the Cold War until its fall in 1989."},
    {"keywords": ["renaissance"], "text": "The Renaissance was a period of cultural, artistic, and intellectual revival in Europe from the 14th to 17th centuries, beginning in Italy."},
    {"keywords": ["world", "war", "1"], "text": "World War I (1914-1918) was a global conflict centered in Europe, involving the Allied and Central Powers, ending with the Treaty of Versailles."},
    {"keywords": ["russian", "revolution"], "text": "The Russian Revolution of 1917 overthrew the Tsarist autocracy and eventually led to the establishment of the Soviet Union."},
    {"keywords": ["space", "race"], "text": "The Space Race was a Cold War-era competition between the United States and Soviet Union to achieve superior spaceflight capability."},
    {"keywords": ["apollo", "11", "moon landing"], "text": "Apollo 11 was the NASA mission that landed the first humans, Neil Armstrong and Buzz Aldrin, on the Moon on July 20, 1969."},
    {"keywords": ["covid", "pandemic"], "text": "The COVID-19 pandemic, caused by the SARS-CoV-2 virus, began in late 2019 and became a global public health crisis affecting nearly every country."},
    {"keywords": ["dot-com", "bubble"], "text": "The dot-com bubble was a period in the late 1990s of excessive speculation in internet-based companies, which crashed in 2000-2001."},
    {"keywords": ["harry", "potter", "rowling"], "text": "Harry Potter is a fantasy book series written by British author J.K. Rowling, following a young wizard's adventures at Hogwarts School."},
    {"keywords": ["charles", "dickens"], "text": "Charles Dickens was a 19th-century English novelist known for works such as Oliver Twist, A Tale of Two Cities, and Great Expectations."},
    {"keywords": ["leo", "tolstoy"], "text": "Leo Tolstoy was a Russian writer widely regarded as one of the greatest novelists, known for War and Peace and Anna Karenina."},
    {"keywords": ["mark", "twain"], "text": "Mark Twain was an American writer known for The Adventures of Tom Sawyer and Adventures of Huckleberry Finn."},
    {"keywords": ["rk", "narayan", "r.k. narayan"], "text": "R. K. Narayan was an Indian author known for setting many of his novels in the fictional South Indian town of Malgudi."},
    {"keywords": ["chetan", "bhagat"], "text": "Chetan Bhagat is a popular contemporary Indian author known for novels like Five Point Someone and 2 States."},
    {"keywords": ["ramayana"], "text": "The Ramayana is an ancient Indian epic that narrates the life of Prince Rama, his wife Sita, and the battle against the demon king Ravana."},
    {"keywords": ["mahabharata"], "text": "The Mahabharata is one of the longest ancient Indian epics, centering on the Kurukshetra War between the Pandavas and Kauravas."},
    {"keywords": ["bhagavad", "gita"], "text": "The Bhagavad Gita is a 700-verse Hindu scripture that is part of the Mahabharata, presenting a dialogue between Prince Arjuna and Lord Krishna."},
    {"keywords": ["nobel", "prize", "literature"], "text": "The Nobel Prize in Literature is awarded annually by the Swedish Academy to an author for outstanding contributions to literature."},
    {"keywords": ["booker", "prize"], "text": "The Booker Prize is a leading literary award for the best novel written in English and published in the UK or Ireland."},
    {"keywords": ["pulitzer", "prize"], "text": "The Pulitzer Prize is an American award recognizing achievements in journalism, literature, and musical composition."},
    {"keywords": ["nobel", "prize"], "text": "The Nobel Prize is a set of annual international awards for outstanding contributions in physics, chemistry, medicine, literature, peace, and economics."},
    {"keywords": ["oscar", "academy", "awards"], "text": "The Academy Awards (Oscars) are annual awards presented by the Academy of Motion Picture Arts and Sciences for excellence in cinema."},
    {"keywords": ["grammy"], "text": "The Grammy Awards are presented annually by the Recording Academy to recognize outstanding achievements in the music industry."},
    {"keywords": ["padma", "shri"], "text": "The Padma Shri is one of India's highest civilian awards, given for distinguished contributions in various fields."},
    {"keywords": ["padma", "bhushan"], "text": "The Padma Bhushan is India's third-highest civilian award, recognizing distinguished service of a high order."},
    {"keywords": ["bharat", "ratna"], "text": "The Bharat Ratna is India's highest civilian award, recognizing exceptional service toward the advancement of art, literature, science, or public service."},
    {"keywords": ["turing", "award"], "text": "The Turing Award is an annual prize given by the Association for Computing Machinery, often called the 'Nobel Prize of Computing.'"},
    {"keywords": ["fields", "medal"], "text": "The Fields Medal is a prestigious award given to mathematicians under 40 for outstanding contributions, often considered the 'Nobel Prize of Mathematics.'"},
    {"keywords": ["rupee"], "text": "The Indian Rupee (INR) is the official currency of India, subdivided into 100 paise."},
    {"keywords": ["dollar"], "text": "The United States Dollar (USD) is the official currency of the United States and the world's primary reserve currency."},
    {"keywords": ["euro"], "text": "The Euro is the official currency used by 20 of the 27 member states of the European Union."},
    {"keywords": ["inflation"], "text": "Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power over time."},
    {"keywords": ["stock", "market"], "text": "A stock market is a marketplace where shares of publicly traded companies are issued, bought, and sold."},
    {"keywords": ["nse"], "text": "The National Stock Exchange (NSE) of India is one of the leading stock exchanges in India, based in Mumbai."},
    {"keywords": ["bse"], "text": "The Bombay Stock Exchange (BSE) is the oldest stock exchange in Asia, located in Mumbai, India."},
    {"keywords": ["rbi"], "text": "The Reserve Bank of India (RBI) is India's central banking institution, responsible for regulating the country's monetary policy and currency."},
    {"keywords": ["hinduism"], "text": "Hinduism is one of the world's oldest religions, originating in the Indian subcontinent, encompassing diverse beliefs, practices, and scriptures like the Vedas."},
    {"keywords": ["islam"], "text": "Islam is a monotheistic religion founded in the 7th century CE by the Prophet Muhammad, with the Quran as its central religious text."},
    {"keywords": ["christianity"], "text": "Christianity is a monotheistic religion based on the life and teachings of Jesus Christ, with the Bible as its central sacred text."},
    {"keywords": ["buddhism"], "text": "Buddhism is a religion and philosophy founded by Siddhartha Gautama (the Buddha) in ancient India, centered on the path to enlightenment and ending suffering."},
    {"keywords": ["sikhism"], "text": "Sikhism is a monotheistic religion founded in the 15th century in Punjab, India, by Guru Nanak, with the Guru Granth Sahib as its central scripture."},
    {"keywords": ["jainism"], "text": "Jainism is an ancient Indian religion that emphasizes nonviolence (ahimsa), truth, and asceticism toward all living beings."},
    {"keywords": ["judaism"], "text": "Judaism is one of the oldest monotheistic religions, originating among the ancient Israelites, with the Torah as its central text."},
    {"keywords": ["diwali"], "text": "Diwali, the festival of lights, is one of the most important Hindu festivals, symbolizing the victory of light over darkness and good over evil."},
    {"keywords": ["holi"], "text": "Holi is a popular Hindu festival celebrating the arrival of spring, known for the throwing of colored powders and water."},
    {"keywords": ["eid"], "text": "Eid refers to two major Islamic festivals, Eid al-Fitr and Eid al-Adha, marking the end of Ramadan and commemorating Ibrahim's willingness to sacrifice his son, respectively."},
    {"keywords": ["chandrayaan"], "text": "Chandrayaan is India's series of lunar exploration missions by ISRO; Chandrayaan-3 successfully landed near the Moon's south pole in 2023."},
    {"keywords": ["mangalyaan"], "text": "Mangalyaan, also known as the Mars Orbiter Mission, was India's first interplanetary mission, successfully reaching Mars orbit in 2014."},
    {"keywords": ["apollo", "program"], "text": "The Apollo program was a series of NASA missions in the 1960s and 1970s that succeeded in landing astronauts on the Moon."},
    {"keywords": ["spacex"], "text": "SpaceX is an American aerospace company founded by Elon Musk in 2002, known for reusable rockets and the Falcon and Starship vehicles."},
    {"keywords": ["voyager"], "text": "Voyager 1 and 2 are NASA space probes launched in 1977 to study the outer planets, now traveling in interstellar space."},
    {"keywords": ["hubble", "telescope"], "text": "The Hubble Space Telescope is a NASA/ESA space telescope launched in 1990, providing detailed images of distant galaxies and cosmic phenomena."},
    {"keywords": ["speed", "of", "light"], "text": "The speed of light in a vacuum is approximately 299,792 kilometers per second, a fundamental constant in physics."},
    {"keywords": ["human", "genome"], "text": "The Human Genome Project, completed in 2003, mapped the complete set of genes in human DNA, advancing medicine and biology."},
    {"keywords": ["plate", "tectonics"], "text": "Plate tectonics is the scientific theory describing the large-scale movement of Earth's lithospheric plates, explaining earthquakes, volcanoes, and mountain formation."},
    {"keywords": ["volcano"], "text": "A volcano is an opening in Earth's crust through which molten rock, ash, and gases escape, often forming a mountain over time."},
    {"keywords": ["earthquake"], "text": "An earthquake is the shaking of the Earth's surface caused by a sudden release of energy in the crust, often along fault lines."},
    {"keywords": ["tsunami"], "text": "A tsunami is a series of large ocean waves usually caused by underwater earthquakes, volcanic eruptions, or landslides."},
    {"keywords": ["renewable", "energy"], "text": "Renewable energy comes from naturally replenishing sources such as sunlight, wind, and water, offering an alternative to fossil fuels."},
    {"keywords": ["solar", "energy"], "text": "Solar energy is power derived from sunlight, captured using technologies such as photovoltaic panels or solar thermal collectors."},
    {"keywords": ["wind", "energy"], "text": "Wind energy is electricity generated by converting the kinetic energy of wind into power using turbines."},
    {"keywords": ["nuclear", "energy"], "text": "Nuclear energy is generated through nuclear fission reactions, producing electricity in nuclear power plants without direct carbon emissions."},
    {"keywords": ["greenhouse", "effect"], "text": "The greenhouse effect is the process by which gases in Earth's atmosphere trap heat from the sun, warming the planet's surface."},
    {"keywords": ["ozone", "layer"], "text": "The ozone layer is a region of Earth's stratosphere that absorbs most of the sun's harmful ultraviolet radiation."},
    {"keywords": ["biodiversity"], "text": "Biodiversity refers to the variety of life on Earth, encompassing the diversity of species, genes, and ecosystems."},
    {"keywords": ["ecosystem"], "text": "An ecosystem is a community of living organisms interacting with each other and their physical environment."},
    {"keywords": ["food", "chain"], "text": "A food chain describes the sequence of organisms through which energy and nutrients pass as one organism eats another."},
    {"keywords": ["wi-fi", "wifi"], "text": "Wi-Fi is a wireless networking technology that allows devices to connect to the internet using radio waves, based on IEEE 802.11 standards."},
    {"keywords": ["bluetooth"], "text": "Bluetooth is a short-range wireless technology standard used for exchanging data between fixed and mobile devices."},
    {"keywords": ["gps"], "text": "GPS (Global Positioning System) is a satellite-based navigation system that provides location and time information anywhere on Earth."},
    {"keywords": ["5g"], "text": "5G is the fifth generation of mobile network technology, offering faster speeds and lower latency than previous generations."},
    {"keywords": ["quantum", "computing"], "text": "Quantum computing is a type of computation that uses quantum-mechanical phenomena such as superposition and entanglement to process information."},
    {"keywords": ["neural", "network"], "text": "A neural network is a computing system inspired by biological brains, consisting of interconnected layers of nodes used in machine learning."},
    {"keywords": ["deep", "learning"], "text": "Deep learning is a subset of machine learning that uses multi-layered neural networks to model complex patterns in data."},
    {"keywords": ["chatgpt", "gpt"], "text": "GPT (Generative Pre-trained Transformer) is a family of large language models developed by OpenAI, powering the ChatGPT conversational assistant."},
    {"keywords": ["transformer", "architecture"], "text": "The Transformer is a neural network architecture introduced in 2017 that relies on self-attention mechanisms, forming the basis of most modern large language models."},
    {"keywords": ["git", "version control"], "text": "Git is a distributed version control system used to track changes in source code during software development."},
    {"keywords": ["github"], "text": "GitHub is a web-based platform for hosting and collaborating on Git repositories, owned by Microsoft."},
    {"keywords": ["linux"], "text": "Linux is a family of open-source Unix-like operating systems based on the Linux kernel, widely used in servers, embedded systems, and cloud computing."},
    {"keywords": ["operating", "system"], "text": "An operating system is system software that manages computer hardware and provides services for running application programs."},
    {"keywords": ["compiler"], "text": "A compiler is a program that translates source code written in a programming language into machine code or another target language."},
    {"keywords": ["mount", "kilimanjaro"], "text": "Mount Kilimanjaro is located in Tanzania and is the highest peak in Africa at 5,895 meters."},
    {"keywords": ["gateway", "of india"], "text": "The Gateway of India is a monumental arch built in Mumbai, India, commemorating the visit of King George V and Queen Mary in 1911."},
    {"keywords": ["red", "fort"], "text": "The Red Fort is a historic Mughal fortress in Delhi, India, built by Emperor Shah Jahan in the 17th century, and a UNESCO World Heritage Site."},
    {"keywords": ["qutub", "minar"], "text": "The Qutub Minar is a 73-meter tall minaret in Delhi, India, built in the early 13th century and a UNESCO World Heritage Site."},
    {"keywords": ["hawa", "mahal"], "text": "The Hawa Mahal, or Palace of Winds, is a palace in Jaipur, Rajasthan, known for its unique honeycomb facade with 953 small windows."},
    {"keywords": ["statue", "of unity"], "text": "The Statue of Unity in Gujarat, India, dedicated to Sardar Vallabhbhai Patel, is the tallest statue in the world at 182 meters."},
    {"keywords": ["namibia", "windhoek"], "text": "Windhoek is the capital of Namibia."},
    {"keywords": ["botswana", "gaborone"], "text": "Gaborone is the capital of Botswana."},
    {"keywords": ["rwanda", "kigali"], "text": "Kigali is the capital of Rwanda."},
    {"keywords": ["malawi", "lilongwe"], "text": "Lilongwe is the capital of Malawi."},
    {"keywords": ["madagascar", "antananarivo"], "text": "Antananarivo is the capital of Madagascar."},
    {"keywords": ["papua new guinea", "port moresby"], "text": "Port Moresby is the capital of Papua New Guinea."},
    {"keywords": ["haiti", "port-au-prince"], "text": "Port-au-Prince is the capital of Haiti."},
    {"keywords": ["dominican republic", "santo domingo"], "text": "Santo Domingo is the capital of the Dominican Republic."},
    {"keywords": ["jamaica", "kingston"], "text": "Kingston is the capital of Jamaica."},
    {"keywords": ["taiwan", "taipei"], "text": "Taipei is the capital of Taiwan."},
    {"keywords": ["brunei", "bandar seri begawan"], "text": "Bandar Seri Begawan is the capital of Brunei."},
    {"keywords": ["east timor", "dili"], "text": "Dili is the capital of East Timor (Timor-Leste)."},
    {"keywords": ["andorra", "andorra la vella"], "text": "Andorra la Vella is the capital of Andorra."},
    {"keywords": ["liechtenstein", "vaduz"], "text": "Vaduz is the capital of Liechtenstein."},
    {"keywords": ["san marino"], "text": "San Marino City is the capital of San Marino."},
    {"keywords": ["vatican"], "text": "Vatican City is an independent city-state and the spiritual center of the Roman Catholic Church, home to the Pope."},
    {"keywords": ["moldova", "chisinau"], "text": "Chisinau is the capital of Moldova."},
    {"keywords": ["belarus", "minsk"], "text": "Minsk is the capital of Belarus."},
    {"keywords": ["north macedonia", "skopje"], "text": "Skopje is the capital of North Macedonia."},
    {"keywords": ["montenegro", "podgorica"], "text": "Podgorica is the capital of Montenegro."},
    {"keywords": ["kosovo", "pristina"], "text": "Pristina is the capital of Kosovo."},
    {"keywords": ["human", "eye"], "text": "The human eye is a sensory organ that detects light and enables vision, converting light into electrical signals interpreted by the brain."},
    {"keywords": ["skin", "organ"], "text": "The skin is the largest organ of the human body, serving as a protective barrier and regulating temperature."},
    {"keywords": ["muscles"], "text": "Muscles are tissues composed of fibers that contract to produce movement, maintain posture, and generate heat in the body."},
    {"keywords": ["periodic", "elements"], "text": "There are currently 118 confirmed chemical elements in the periodic table, ranging from hydrogen to oganesson."},
    {"keywords": ["antibiotic"], "text": "An antibiotic is a type of medicine that fights bacterial infections by killing bacteria or preventing their growth, first discovered as penicillin by Alexander Fleming."},
    {"keywords": ["penicillin"], "text": "Penicillin, discovered by Alexander Fleming in 1928, was the first widely used antibiotic, revolutionizing the treatment of bacterial infections."},
    {"keywords": ["theory", "of relativity"], "text": "Einstein's theory of relativity, comprising special and general relativity, describes the relationship between space, time, gravity, and motion."},
    {"keywords": ["periodic", "law"], "text": "The periodic law states that the properties of chemical elements are periodic functions of their atomic numbers, forming the basis of the periodic table."},
    {"keywords": ["stock", "exchange", "nyse"], "text": "The New York Stock Exchange (NYSE) is the largest stock exchange in the world by market capitalization, located on Wall Street."},
    {"keywords": ["nasdaq"], "text": "NASDAQ is an American electronic stock exchange known for listing many major technology companies."},
    {"keywords": ["world", "bank"], "text": "The World Bank is an international financial institution that provides loans and grants to developing countries for capital projects."},
    {"keywords": ["international", "monetary", "fund", "imf"], "text": "The International Monetary Fund (IMF) is an international organization that promotes global monetary cooperation and financial stability."},
    {"keywords": ["european", "union"], "text": "The European Union (EU) is a political and economic union of 27 member states located primarily in Europe."},
    {"keywords": ["nato"], "text": "NATO (North Atlantic Treaty Organization) is a military alliance of North American and European countries established in 1949."},
    {"keywords": ["who", "world health"], "text": "The World Health Organization (WHO) is a specialized agency of the United Nations responsible for international public health."},
    {"keywords": ["unesco"], "text": "UNESCO (United Nations Educational, Scientific and Cultural Organization) promotes international collaboration in education, science, and culture, and designates World Heritage Sites."},
]


def retrieve(query: str, min_score: int = 1):
    """
    Very simple keyword-overlap retrieval: lowercase the query, check how many of
    each knowledge-base entry's keywords appear in it, return the best-matching
    entry's text if it clears min_score, else None.
    """
    query_lower = query.lower()
    best_entry = None
    best_score = 0

    for entry in KNOWLEDGE_BASE:
        score = sum(1 for kw in entry["keywords"] if kw in query_lower)
        if score > best_score:
            best_score = score
            best_entry = entry

    if best_entry and best_score >= min_score:
        return best_entry["text"]
    return None